/**
 * Generate TypeScript types from JSON schemas.
 *
 * Run: node tools/generate-types.mjs
 * Output: backend/src/generated/schema-types.ts
 *
 * Types are generated by json-schema-to-typescript and must not be
 * edited by hand. Re-run this script after any schema change.
 */
import fs from 'node:fs';
import path from 'node:path';
import { compile } from 'json-schema-to-typescript';

const schemasDir = path.resolve('schemas');
const outputFile = path.resolve('backend/src/generated/schema-types.ts');
const outputDir = path.dirname(outputFile);

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const schemaFiles = [
  'spot.schema.json',
  'ruleset.schema.json',
  'published-forecast.schema.json',
  'normalized-timeline.schema.json',
];

const options = {
  bannerComment:
    '/* eslint-disable */\n' +
    '/**\n' +
    ' * AUTO-GENERATED — do not edit by hand.\n' +
    ' * Run `npm run generate:types` after schema changes.\n' +
    ' * Source: tools/generate-types.mjs\n' +
    ' */',
  style: { singleQuote: true, semi: true },
  strictIndexSignatures: true,
  unknownAny: false,
};

let combined = options.bannerComment + '\n\n';

for (const file of schemaFiles) {
  const schema = JSON.parse(fs.readFileSync(path.join(schemasDir, file), 'utf8'));
  // Provide the $defs to the resolver via the schema itself
  const ts = await compile(schema, schema.title ?? file, options);
  // Strip the banner from subsequent schemas
  const stripped = ts.replace(/\/\*[\s\S]*?\*\/\n/, '').trim();
  combined += `// ─── ${file} ───────────────────────────────────────────\n`;
  combined += stripped + '\n\n';
  console.log(`generated types for: ${file}`);
}

fs.writeFileSync(outputFile, combined, 'utf8');
console.log(`written: ${outputFile}`);
